### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.75 GiB total capacity; 6.37 GiB already allocated; 39.12 MiB free; 6.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

### ISSUE THREAD

**Issue by gauraviiita** [WEIRDLabUW/urdformer#6]
Hello,
I am trying to run this simple command but i am getting CUDA out of memory.

python demo.py --scene_type object --texture

What should I change so that I will not get this error.

Thanking you

**Comment by gauraviiita** [comment]
The issue has been successfully resolved. The problem arose due to a conflict with CUDA.

My system is configured with an RTX 4060 and CUDA 12.4. Initially, I installed torch==1.12.1+cu113, but this caused a runtime error.

To address this, I created a new virtual environment and installed torch 2.1.0+cu121. After this, the problem was resolved, and the code is running perfectly.

I also installed mmcv==2.1.0 using the following command:
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html

Additionally, the code requires numpy to be below version 2.0, so I installed numpy 1.26.0.

Thank you!
